antrop_arms:
  gazebo_ros_control:
    pid_gains:
      base_shoulder_right_pitch_joint:
        p: 200.0
        i: 0.0
        d: 50.0
      base_shoulder_right_joint:
        p: 225.0
        i: 0.0
        d: 60.0
      shoulder_elbow_right_joint:
        p: 10.0
        i: 0.0
        d: 0.2
      elbow_forearm_right_joint:
        p: 200.0
        i: 0.0
        d: 2.0
      base_shoulder_left_pitch_joint:
        p: 200.0
        i: 0.0
        d: 50.0
      base_shoulder_left_joint:
        p: 225.0
        i: 0.0
        d: 60.0
      shoulder_elbow_left_joint:
        p: 10.0
        i: 0.0
        d: 0.2
      elbow_forearm_left_joint:
        p: 200.0
        i: 0.0
        d: 2.0

